name: Publish to NPM
on:
  release:
    types: [created]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build library
        run: |
          docker compose run --rm build npm run build

      - name: Publish library
        run: |
          docker compose run --rm -e NODE_AUTH_TOKEN=${{ secrets.NPM_TOKEN }} build npm publish --access public

      - name: Build demo
        run: |
          docker compose run --rm demo npm run build

      - name: Deploy demo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: demo/build
